Add support for kind, status, instrumentation library, links, events and state data for traces
grafana/clickhouse-datasource pull request #1043
Opened 2024-11-01 16:29 UTC by benceszikora

This PR adds support for the kind, status, instrumentation library, links, events and state fields in the trace panel in Grafana. This will bring the plugin to feature parity with what Tempo can offer today.

2024-11-01 16:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/clickhouse-datasource?pullRequest=1043) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/clickhouse-datasource?pullRequest=1043) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/clickhouse-datasource?pullRequest=1043) it.</sub>

2024-11-01 23:41 UTC, SpencerTorres requested changes
Thank you for the contribution! Glad to see expanded functionality for the trace columns. I've added a note regarding the intended table schema

2024-11-01 23:41 UTC, SpencerTorres commented on src/otel.ts
> +    [ColumnHint.TraceInstrumentationLibraryName, 'InstrumentationLibraryName'],
I noticed theres a few columns defined in `otel.ts` that don't exist on the [ClickHouse OTel exporter default schema](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/eac16d39fcf5d201894b9babae3eff79dce4e58c/exporter/clickhouseexporter/example/default_ddl/traces.sql). The intent of these definitions is to match as closely as possible to this table schema for a better out of the box experience.

Should we look into adding these columns to the otel exporter?

Also note that `State` is defined too, but on the table it is called `TraceState`.

2024-11-07 13:53 UTC, Sup3rGeo commented
Also AFAIU In the default schema Links is a Nested table and you need to select the fields individually:

```
 arrayMap(
  (traceid, spanid, attributes) -> tuple(
                     traceid,
                     spanid,
                     arrayMap(
                       key -> map('key', key, 'value', attributes[key]),
                       mapKeys(attributes)
                     )
                   )::Tuple(traceID String, spanID String, tags Array(Map(String, String)))
                   , Links.TraceId, Links.SpanId, Links.Attributes
  ) AS references
```

2024-12-03 22:06 UTC, jwhitaker-gridcog commented
> Also AFAIU In the default schema Links is a Nested table and you need to select the fields individually

@Sup3rGeo not disputing the table schema, but `arrayMap(l -> ..., Links)` does work here - is it possible this is a newer clickhouse feature?

@SpencerTorres  @benceszikora  is it worth splitting the bits of this PR that can work with the current schema into something that's mergeable now? In my case I'm itching for span events to be supported, and this achieves that out of the box which is really nice.

2025-01-07 22:44 UTC, SpencerTorres commented
> is it worth splitting the bits of this PR that can work with the current schema into something that's mergeable now?

Yes, there's some parts of this that need changing. I don't mind picking apart the code myself for it, but I want to make sure the author is okay with that (@benceszikora)

2025-02-03 16:57 UTC, harryjph reviewed
Hey everyone! I've updated the code to be based on the [OTel Collector Schema](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/eac16d39fcf5d201894b9babae3eff79dce4e58c/exporter/clickhouseexporter/example/default_ddl/traces.sql) as requested, and rebased the PR onto main to incorporate https://github.com/grafana/clickhouse-datasource/pull/1128, which was merged last week. I've also updated the test cases to cover code merged in that PR.

I've left a couple of comments explaining the changes which aren't simple column addition.

2025-02-03 16:57 UTC, harryjph commented on src/data/sqlGenerator.ts
> -    selectParts.push(`arrayMap((name, timestamp, attributes) -> tuple(name, toString(toUnixTimestamp64Milli(timestamp)), arrayMap( key -> map('key', key, 'value', attributes[key]), mapKeys(attributes
There are two ways in ClickHouse to define a Nested Table, controlled by the [`flatten_nested`](https://clickhouse.com/docs/en/operations/settings/settings#flatten-nested) setting at column creation time.

The query as previously written does not work when `flatten_nested=0`, as ClickHouse does not recognise the sub-columns such as `Events.Names` in this mode.

The rewritten query should work with either mode, as ClickHouse will recognise `Events` as one column even when it has been flattened.

2025-02-03 16:57 UTC, harryjph commented on src/components/queryBuilder/views/TraceQueryBuilder.tsx
> +  const onColumnPrefixChange = (name: keyof TraceQueryBuilderState, columnHint: ColumnHint) => {
This change is necessary since at the moment, you cannot type into the "Events Prefix" field in the column selection form.

This function generates a `SelectedColumn` struct for the arbitrary input, which is necessary since when `flatten_nested=1`, the `ColumnSelect` component recognises the `Events` column as multiple sub-columns.

2025-02-24 18:55 UTC, benceszikora commented
@SpencerTorres with @harryjph's changes this PR should now conform to the same schema as the OTel Collector. Are there any changes you would suggest before this can be merged?

2025-03-25 13:28 UTC, ValentinLvr commented on src/views/CHConfigEditor.tsx
> +          onLinksPrefixColumnChange={c => onTracesConfigChange('linksColumnPrefix', c)}
Typo here I guess
```suggestion
          onLinksColumnPrefixChange={c => onTracesConfigChange('linksColumnPrefix', c)}
```

2025-03-25 15:17 UTC, ValentinLvr commented
Just tested out this fork locally and note that span link redirection is not working so far.

When you click on the link it basically redirects you to the same trace instead of the one linked.
Echoes to [this issue](https://github.com/grafana/clickhouse-datasource/issues/977)

![Screenshot 2025-03-25 at 16 08 17](https://github.com/user-attachments/assets/feb7031b-27e2-4b1f-911c-263c82e1480f)

2025-03-26 06:03 UTC, SpencerTorres commented
Hello! I appreciate all the changes and comments everyone contributed here.

The main value of this PR was solving how to properly decode these `Nested` columns, and it seems like this was solved for multiple cases (`flatten_nested` `=` `0`/`1`). Thank you for testing that

There were some large structural changes I wanted to address before merging this into the main branch, and instead of writing a bunch of suggestions I decided to fix them myself in a different PR: #1208

These are mainly related to how the components are used, along with fixing some test cases and adding flexibility. If you have any more comments related to the code of this PR, I would recommend writing them over there where I can address them asap.

Hopefully we can get this merged soon now that everything is working smoothly 👌

2025-03-26 06:30 UTC, SpencerTorres commented
> Just tested out this fork locally and note that span link redirection is not working so far.
> 
> When you click on the link it basically redirects you to the same trace instead of the one linked. Echoes to [this issue](https://github.com/grafana/clickhouse-datasource/issues/977)
> 
> ![Screenshot 2025-03-25 at 16 08 17](https://private-user-images.githubusercontent.com/50106974/426597002-feb7031b-27e2-4b1f-911c-263c82e1480f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI5Njc4NzcsIm5iZiI6MTc0Mjk2NzU3NywicGF0aCI6Ii81MDEwNjk3NC80MjY1OTcwMDItZmViNzAzMWItMjdlMi00YjFmLTkxMWMtMjYzYzgyZTE0ODBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzI2VDA1MzkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkZmEyZGVlNzRmMDgyYzJiNjBkMTllN2JjM2E4YzE1NGI2NTRkYTllZmIyYWUzMTc4ZGFkM2Q1ZDY2Yjc5MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wgZt-Y1BYTnqdST36T-FcNqqyRERJzI1DnnuIGzdnA8)

@ValentinLvr Hey! I finally found a sample row that shows this. Let's put it into a new issue, this might have something to do with the linking. Maybe even a conflict with our existing `TraceId` link. I'll ask the Grafana team

2025-05-12 13:23 UTC, closed without merging