Do not control SqlEditor height
grafana/clickhouse-datasource pull request #687
Opened 2024-02-07 11:24 UTC by mshustov

closes https://github.com/grafana/clickhouse-datasource/issues/684

There is a bug in logic that on every change in the editor calls `saveChanges({expand:true})`, which resets the `rawSql` value back to the original state.
Instead of fixing this bug, I checked how Grafana handles this logic itself. From [this example](https://github.com/grafana/grafana/blob/f59e76d54b0f5ea11e23f2f59eb3281682c7d1d0/public/app/plugins/datasource/tempo/traceql/TraceQLEditor.tsx#L81), it looks like the built-in Grafana editor handles height updates inside `CodeEditor` component, so I removed the external logic to manage component height.

### Changelog
Remove manual expansion of SqlEditor.

2024-02-13 18:50 UTC, asimpson requested changes
:+1: looks good to me, thanks!

Just one nit and I'll approve.

2024-02-13 18:50 UTC, asimpson commented on src/components/SqlEditor.tsx
> +      console.log('contentHeight', contentHeight, 'width', width);
```suggestion
```
nit: we don't need this right?

2024-02-14 18:51 UTC, asimpson approved these changes

2024-02-15 12:53 UTC, asimpson commented
@mshustov Looks like it. The build passed though which is what I care about. Can you merge `main` and I can merge the PR?

2024-02-18 11:21 UTC, mshustov commented
@asimpson could you merge?

2024-02-20 19:51 UTC, merged